services:
  redis:
    image: redis:alpine
    container_name: redis_service
    networks:
      - api_network

  nginx:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "8080:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html:ro
      - ./nginx_service/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - session
    networks:
      - api_network

  memory:
    container_name: memory_service
    build:
      context: ./memory_service
      dockerfile: Dockerfile
    image: memory_service:latest
    networks:
      - api_network

  ppu:
    container_name: ppu_service
    build:
      context: ./ppu_service
      dockerfile: Dockerfile
    image: ppu_service:latest
    networks:
      - api_network

  cartridge:
    container_name: cartridge_service
    build:
      context: ./cartridge_service
      dockerfile: Dockerfile
    image: cartridge_service:latest
    networks:
      - api_network

  input:
    container_name: input_service
    build:
      context: ./input_service
      dockerfile: Dockerfile
    image: input_service:latest
    networks:
      - api_network
  
  cpu:
    container_name: cpu_service
    build:
      context: ./cpu_service
      dockerfile: Dockerfile
    image: cpu_service:latest
    networks:
      - api_network

  session:
    container_name: session_service
    build:
      context: ./session_service
      dockerfile: Dockerfile
    image: session_service:latest
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
